### ISSUE TITLE
Install Review GitHub app and set up secrets

### ISSUE THREAD

**Issue by Bullrich** [polkadot-fellows/xcm-format#65]
To properly install review-bot, like requested in https://github.com/polkadot-fellows/xcm-format/issues/62#issuecomment-2161233184, we first need to have the GitHub app used in the runtimes repository.

As you can see in the [GitHub Action Review Bot](https://github.com/polkadot-fellows/runtimes/blob/main/.github/workflows/review-bot.yml), the secrets `REVIEW_APP_ID` and `REVIEW_APP_KEY` have been installed in that repository.

We need an admin to:
- Install the Review App with in this repository.
- Set the `REVIEW_APP_ID` secret in this repository.
- Set the `REVIEW_APP_KEY` secret in this repository.

This are the required steps to install Review-Bot.

**Comment by Bullrich** [comment]
@pavelsupr manages the bot in Parity's org, I remember that he provided both the app id and generated a private key when we installed it in the runtimes repository.

Pavel, could you please generate a new private key and share both the key and the app id with Basti for the app `Parity-Review-Bot`?

Once @bkchr has these, he can [set them as repository secrets](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions) and then I can port the Review-Bot configuration file.

Thanks!

**Comment by pavelsupr** [comment]
Hey @Bullrich @bkchr , in the past the ReviewBot app id and key were already issued for the Fellowship org and provided to Basti. I'll send a copy of them to Basti once again via 1Password.

**Comment by bkchr** [comment]
Ty @pavelsupr.

@Bullrich I created the env variables as requested.

**Comment by Bullrich** [comment]
> Ty @pavelsupr.
> 
> @Bullrich I created the env variables as requested.

Thank you. I created https://github.com/polkadot-fellows/xcm-format/pull/66

I tried to use more of the score system to make it more attractive for lower ranks to participate, but feel free to request any changes.
