### ISSUE TITLE
Install Fellowship-merge-bot in the repository

### ISSUE THREAD

**Issue by Bullrich** [polkadot-fellows/xcm-format#67]
Same as #65, but because the [fellowship-merge-bot](https://github.com/apps/fellowship-merge-bot) belongs to the fellowship so this has to be done by an admin.

We need an admin to:
- Install the [fellowship-merge-bot](https://github.com/apps/fellowship-merge-bot) with in this repository.
- Set the `MERGE_APP_ID` secret in this repository.
- Set the `MERGE_APP_KEY` secret in this repository.

## How to obtain the secrets

- Go to the settings of the organization
- Go to developers settings > `GitHub apps`
- Select the bot and click `Edit`
- The **App ID** should be at the top. 
  - Copy this values to the `MERGE_APP_ID` secret.
- Scroll down until **Private keys**
- Generate a new one
  - Copy its content to the `MERGE_APP_KEY` secret.

**Comment by bkchr** [comment]
Done

**Comment by acatangiu** [comment]
@Bullrich the installed bot doesn't seem to be working: https://github.com/polkadot-fellows/xcm-format/pull/61#issuecomment-2225983179
